### ISSUE TITLE
AST - Can essential dignity display like Celestial Intersection Does?

### ISSUE THREAD

**Issue by Willnoble83** [Airex/ffxiv-fightline#1]
Hey, love the site just wanted to leave a bit of feedback for how AST abilities display.

I love how celestial intersection handles the fact its 2 charges (Expands to have both charges on different lines). Could this be expanded to essential dignity as that is also 2 charges? Essential dignity is a lot harder to see at a glance when its back up as it only displays as a dot instead of a bar.

![image](https://user-images.githubusercontent.com/24992749/155158042-31aeb7b8-9522-47f2-96b6-0157bf3d3032.png)

Many thanks for your work!

**Comment by Airex** [comment]
I have made some changes. You can check they  work for you

**Comment by Willnoble83** [comment]
Yeah its all working fine. Thank you!
