### ISSUE TITLE
Change opacity of the SidePanel.

### ISSUE THREAD

**Issue by ShinoMythmaker** [Airex/ffxiv-fightline#16]
The sidepanel has a slight opacity t it. Personally i think its a bit distracting and i dont need to see the content beneath it. Especially in darkmode its kind of distracting.

![image_2023-01-30_152631080](https://user-images.githubusercontent.com/112497873/215504053-e267bbc9-0121-4565-9ac2-17caf7ff991a.png)

**Comment by Airex** [comment]
@Shinokage107 
should looks better now
