### ISSUE TITLE
An AI approach to make an automated mitigation Plan. 

### ISSUE THREAD

**Issue by ShinoMythmaker** [Airex/ffxiv-fightline#17]
This istn something i think thats in dire need, i just think it would be dope. 

I imagine it that u can select ur party composition and a Boss Template and the AI gives u a mitigation plane. It doesnt have to be perfect i just think it would be cool to see how an AI would approach things and maybe give us a few more ideas how to handle what situations. 

Later on this could be Extended to also cover Buffs to better understand or see if delaying buff windows in some fights is even worth.

**Comment by Airex** [comment]
I am not familiar with any of AI engines to be able to implement it.
Any AI requires modeling and training to fit some needs. This requires sets of data to train AI on or very good reward based policy to maximize model outputs.
This can be fun to dig in, but require a lot of time to learn, investigate and implement.
I am open for suggestion or cooperation/pull requests to improve tool
