### ISSUE TITLE
Some abilities cannot be moved to before pull time

### ISSUE THREAD

**Issue by williamgiang** [Airex/ffxiv-fightline#24]
eg. DRK's Delirium cannot be be moved any earlier than 0s on timeline.

Some of these cooldowns needs to be used earlier to account for boss phasing and optimising occurrences throughout the fight.

**Comment by Airex** [comment]
Hello there,

Thank you for bringing this issue to our attention. We are glad to inform you that we have fixed the problem, and DRK's Delirium can now be moved earlier on the timeline as needed to optimize occurrences throughout the fight, including accounting for boss phasing.

We appreciate your feedback and are always here to help with any other issues or concerns you may have. Please don't hesitate to reach out to us if you need any further assistance.

Thank you for using our service!
