### ISSUE TITLE
Sage - Kerachole active duration isn't correct

### ISSUE THREAD

**Issue by Willnoble83** [Airex/ffxiv-fightline#27]
Kerachole for sage is 15s duration with a 30s cooldown however it appears to only be showing the green bar (which I believe to be how long it is in effect) for 10 seconds.

Visible on this timeline: https://www.ffxiv-fightline.com/0b718124856842689ccc4873f7400b8d

![image](https://user-images.githubusercontent.com/24992749/149395148-43d84f26-6251-408f-b3c2-5ff0aa91fb88.png)

**Comment by Airex** [comment]
Fixed
