### ISSUE TITLE
[FEATURE] - Couple of added functionality for shield interactions

### ISSUE THREAD

**Issue by bidaumm** [Airex/ffxiv-fightline#39]
1. Anything that gives a shield - once it intersects with an ability.. (possibly using AoE tag?) the bar changes to more of a faded option to show "this might remove the shield"  I've done a loose mockup with paint.net in the screenshot to show what I'm thinking.
![image](https://user-images.githubusercontent.com/30007328/228402327-4c184831-d27d-4783-8453-d9d9dd6095ee.png)

2. is it possible to add logic that interacts between deployment tactics and adloqium? Currently it only shows the % shield as a solo ability for the SCH thats casting it.. which is fine for initial logic. But if adlo is cast and deployment is cast during the buff duration.. additional logic to change the % shield to apply to "Party" vs "SCH" single targetted.

![image](https://user-images.githubusercontent.com/30007328/228402509-02f9f0cf-83ed-49ea-a726-7f1bfa9fda62.png)

This screenshot is using the same data above as an example of how its working currently. 

Probably some other logic interactions to consider for both suggestions such as... is the boss ability an aoe and will fading only work for abilities that are aoe.... etc etc etc.

**Comment by Airex** [comment]
Both features are implemented.
@bidaumm 
Please create separate tickets for each feature, bug, etc.
