### ISSUE TITLE
[BUG] Oblation Defensive Calc when on two Targets

### ISSUE THREAD

**Issue by bidaumm** [Airex/ffxiv-fightline#45]
I've found a bug that's affecting oblation.
It only seems to calculate it once.. even if its been cast on two targets.
See below for more info
https://www.ffxiv-fightline.com/39ed4d4076b342cd9e7bb9dfffbf41ce
When cast on both WAR and DRK.. only showing 10% for WAR
![image](https://user-images.githubusercontent.com/30007328/231438819-ed492963-18a6-431e-972b-e3cbc515cd6d.png)
Defensive table is also only showing cast on WAR
![image](https://user-images.githubusercontent.com/30007328/231438996-f99df7b4-a194-417b-b5be-52dee235e773.png)

When removing Oblation cast on WAR 10% shows on DRK now
![image](https://user-images.githubusercontent.com/30007328/231439061-c8c7ddaf-b4d6-443d-8cfd-261f80d0fd33.png)
and table updates to show DRK
![image](https://user-images.githubusercontent.com/30007328/231439125-45e3873b-5f25-4dd4-bfcc-edd313da30b3.png)

**Comment by Airex** [comment]
fixed in new release
