### ISSUE TITLE
Adding the ability to add Mitigation etc directly from the Tooltip 

### ISSUE THREAD

**Issue by ShinoMythmaker** [Airex/ffxiv-fightline#6]
So i love ur tool but i wish u could simply drag and drop available abilitys into the timeline. 

Currently i dont see any other way to add abilitys to the timeline other then doubleclicking in the right row.

**Comment by Airex** [comment]
Hi @Shinokage107 ,
Can you provide use case when double click does not works well for you?
Or maybe I do not catch your way to work with timeline
Thank you

**Comment by Airex** [comment]
@Shinokage107 
By tooltip do you mean side panel?

**Comment by ShinoMythmaker** [comment]
yes the side panel. I cant just double click it there to add it. The only way to add an ability to the timeline is by doubleclicking the currect row. wich sometimes is a bit difficult. I think it would be easier to just click on a boss cats, see what mitigation is available and then select the ability/mitigation u want to have there

**Comment by Airex** [comment]
@Shinokage107 
Oh, ok
That was initial idea behind Available mitigations section. The only question is to guess at what exactly time to add selected ability at. It could be as early as possible to cover selected boss attack or as later as possible, or closer to the middle of ability duration. But any way it can be adjusted later with  drag & drop. If this is what you expect then I will implement this with just clicking on that ability in sidepanel

**Comment by Airex** [comment]
@Shinokage107 
Feature you requested is live now.
You feedback is welcome and appreciated.

**Comment by ShinoMythmaker** [comment]
Thats Awesome, i love it. Thank u for the fast implementation. One more thing would be to have options for the problem u mentioned. So that u can have a setting for when the mitigation should be casted. Alternatively there could be a "smart" option, where an algorythm decieds where to put it for max coverage. 

For an example. lets take P5S. When i select the first Sonic howl and place a shield samba there an algorythm could figure out that when placed right the shield samba can cover Not only Sonic Howl but also Ruby Glow right after. Thus adjusting where it would drop it. 

But i think for general use its already good enough :3

**Comment by Airex** [comment]
@Shinokage107 
As bonus same actions are available from table view
![image](https://user-images.githubusercontent.com/302188/215550112-383e34a5-380f-4f79-ab45-e6c9fa6aaf41.png)
