### ISSUE TITLE
[BUG] Multiple entries in "Damage" import being created for same ability

### ISSUE THREAD

**Issue by bidaumm** [Airex/ffxiv-fightline#65]
a minor bug I see often when using the damage import from fflogs import 
It ends up splitting the same attack into two or more entries, with the damage numbers for each player split among the entries.

fflogs
https://www.fflogs.com/reports/69dWCvnXq3PzGBh7#fight=last

example import showing this with the ultima hit @ 4:09
https://www.ffxiv-fightline.com/273e24ddf917462cac25251a4bd36490

![image](https://github.com/Airex/ffxiv-fightline/assets/30007328/915464b2-34a5-453c-942b-91a7119064ab)
![image](https://github.com/Airex/ffxiv-fightline/assets/30007328/9728409a-61a7-447e-951d-7868ad0e2818)

**Comment by Airex** [comment]
@bidaumm Looks like fixed, import now looks more clear
