### ISSUE TITLE
Could you pleasee add Chinese into this tool?

### ISSUE THREAD

**Issue by hikarievo** [Airex/ffxiv-fightline#7]
I'm a ffxiv player from China. I find this tool occasionally and I really like it, hoping Chinese could be added.
You can get Chinese game data from this repo: https://github.com/thewakingsands/ffxiv-datamining-cn
and I can support you with UI translations by Crowdin or jsut create a PR
Hope you will consider this idea.

**Comment by Airex** [comment]
@hikarievo 
Hi, 
Sure this idea is great.
You can help me translate UI
I have added https://github.com/Airex/ffxiv-fightline/blob/master/FightTimeLine/ClientApp/src/assets/i18n/lang_cn.json, one can use this file and update with appropriate translated values
I will add translation to abilities as well.
One issue I can see I did not find any CN value for ability description/tooltip on web resource you provided, maybe I missed something.

**Comment by Airex** [comment]
@hikarievo 
Abilities in Chinese are already live.

**Comment by Airex** [comment]
@hikarievo 
any updates?

**Comment by hikarievo** [comment]
> 

Sorry for the lateness, I've been a bit busy these days, I'll check it ASAP, 2~3 days more probably.

**Comment by hikarievo** [comment]
Progress has exceeded expectations with the help of my friends, it should be correct that may need more checking after the changes are released.
Some friends of mine are also interested in this project and want to contribute, if you need more help, let me know.

BTW, these is another typo in line 52: sign → sing

**Comment by Airex** [comment]
Translations are live
