### ISSUE TITLE
Missing SGE actions in defensive table view

### ISSUE THREAD

**Issue by Huderon** [Airex/ffxiv-fightline#71]
Physis II and Soteria don't seem to appear in the defensive table view, even with `show healing` enabled

![6GCBum3](https://github.com/Airex/ffxiv-fightline/assets/92663142/1a37f1b6-4535-4b26-8171-028c7d3c9c2d)

**Comment by Airex** [comment]
@Huderon 
should be fixed

**Comment by Huderon** [comment]
Yepyep, that seems to have done it. Thanks

**Comment by Huderon** [comment]
Hey, sorry to reopen. I was sure I checked it this morning, but I guess I rushed it a bit. After the fix you released, the icons currently appear when the timeline is opened as a standalone table, but not in the table view modal

**Comment by Airex** [comment]
I have checked without any modifications and can see it like this
![image](https://github.com/Airex/ffxiv-fightline/assets/302188/39577547-022c-4573-b0fc-77025a4193c8)
Pls, try to do hard refresh of page and open again
also would be good to see url to your example for more details
thank you

**Comment by Huderon** [comment]
Ah, that does seem to have been the issue. I had another copy of the sheet open in another tab group, which I'd forgotten about; that might have also been a problem.

I was a bit thrown off, as even after creating new fight lines, they seemed to be missing, but that's no longer the case.

Thanks again. Sorry for the false alarm
