### ISSUE TITLE
[BUG] Boss attacks erronously have 30 minutes added to them based on system timezone

### ISSUE THREAD

**Issue by endmymisery** [Airex/ffxiv-fightline#73]
As the title suggests:
When the system's timezone is set to one with a half hour difference from UTC (e.g.: NST), boss attacks (both imported and newly created) will have 30 minutes added to them. 
For example, an attack that happens at 1:00 will be imported at 31:00.
Attempting to create an attack at 1:00 by clicking on the timeline will attempt to create it at 31:00.
This bug also applies to saved timelines.

Changing the system's timezone appears to fix this issue.

**Comment by Airex** [comment]
@endmymisery 
I will take a look shortly

**Comment by Airex** [comment]
@endmymisery 
Pls, take a look as I have deployed a fix

**Comment by endmymisery** [comment]
Required a few cache clears and page refreshes to get working but this issue appears to be fixed! Thanks!
