### ISSUE TITLE
GNB Rampart and Reprisal duration wrong on higher levels

### ISSUE THREAD

**Issue by sectax** [Airex/ffxiv-fightline#83]
**Issue**
GNB receives increased duration to Rampart and Reprisal at level 94 and and 98 respectively. This is not reflected in the tool.

**Cause**
This seems to be beacuse `GNB.ts` has no import for `tankSharedTraits`, which contain the traits granting this increased duration.

**Comment by Airex** [comment]
@sectax 
Fixed
Thank you
