### ISSUE TITLE
Scholar's Seraphism ability

### ISSUE THREAD

**Issue by UnaCurita** [Airex/ffxiv-fightline#85]
shows White Mage Divine Caress ability description, and does not reflect it's real duration on the timeline, pretty sure there are other dawntrail healer abilities with wrong descriptions. please check, thank you.

**Comment by Airex** [comment]
@UnaCurita 
I have updated wrong data you mentioned.
I will do my best to review other abilities, if you know about other cases, feel free to mention them in this or other ticket
Thank you
